tree_goals:
  - {x: 1.0, y: 2.0}
  - {x: 3.0, y: 1.5}
  - {x: 5.0, y: 2.5}

arm_positions:
  - [0.1, -1.0, 1.1, 0.4, 0.0, 0.0]
  - [0.2, -1.1, 1.0, 0.5, 0.0, 0.0]
  - [0.3, -1.2, 0.9, 0.6, 0.0, 0.0]

temperature_threshold: 10.0

home_joint_position: [0.0, -0.8, 1.2, 0.3, 0.0, 0.0]
